### ISSUE TITLE
Invite code or admin approval?

### ISSUE THREAD

**Issue by poVoq** [matheusfillipe/ldap-signup#1]
Would it be possible to add some way to restrict the registration with something like shared invite codes and/or maybe manual approval by a LDAP admin?

**Comment by matheusfillipe** [comment]
@poVoq I believe you can have manual confirmation from entirely from ldap side. Using LAM plugin set the default for new accounts to be pending.

For the invite token, this branch does it: https://github.com/matheusfillipe/ldap-signup/tree/special_auth

You generate an invite code with `php create_token.php`.
