### ISSUE TITLE
Possible to disable captcha?

### ISSUE THREAD

**Issue by poVoq** [matheusfillipe/ldap-signup#2]
I am having trouble with the captcha generation, not sure why it is failing (maybe due to Redis not having a password???),

But for testing purposes it would be nice to be able to disable the captcha all together. Since I use the special auth branch I am not too concerned about spam sign-ups without captcha.

Thanks!

**Comment by matheusfillipe** [comment]
Can you give me more details about how is it failing? Is it always saying "wrong captcha" or ?? Redis is only used in the email confirmation so it is required, but shouldn't affect the captcha. You could try setting up a password in your redis? 

If you have problems with the email confirmation you can also try setting `$REDIS_PASS = NULL` or comenting out this line of code to see if it helps: https://github.com/matheusfillipe/ldap-signup/blob/503722cf7459d427bec7f7b452324887aa6b2528/redis.php#L7 if you don't have a password.

As of optionally disabling captcha, it is a feature that would make sense but unfortunately i dont have it implemented. You can try to modify the code though, probably just commenting/removing these lines out https://github.com/matheusfillipe/ldap-signup/blob/503722cf7459d427bec7f7b452324887aa6b2528/index.php#L123-L125 
https://github.com/matheusfillipe/ldap-signup/blob/503722cf7459d427bec7f7b452324887aa6b2528/index.php#L210-L212

And then remove from the templates: https://github.com/matheusfillipe/ldap-signup/blob/503722cf7459d427bec7f7b452324887aa6b2528/templates/register.htm#L73-L84
